### ISSUE TITLE
which is the inner loop?

### ISSUE THREAD

**Issue by Franklin-Yao** [hytseng0509/CrossDomainFewShot#11]
Hi,

I read your papers several times and I think optimizing the model params is the inner loop and optimizing the ft layers is the outer loop. But I am not 100% sure. What do you think?

**Comment by hytseng0509** [comment]
Yeah, if you view our approach from the perspective of the [MAML](https://arxiv.org/pdf/1810.09502.pdf) family.
However, please note that the MAML approaches only update the outer-loop parameters, while we jointly update both the model parameters (you call inner-loop) and FT layers (you call outer-loop) during the training stage.
