### ISSUE TITLE
About the pre-trained backbone

### ISSUE THREAD

**Issue by xzhangeb** [hytseng0509/CrossDomainFewShot#2]
Hello,
Thanks for your work! I have one question for the pre-trained Resnet-10 backbone: did you use different hyper parameters to train this backbone or we can just get the same by running the code "train_baseline.py" where I see you use default Adam optimizer training 400 epochs?

**Comment by hytseng0509** [comment]
Hi,

We use the default hyper-parameters to train the pre-trained feature encoder (i.e., Adam, 400 epochs).
