### ISSUE TITLE
About the Plantae dataset

### ISSUE THREAD

**Issue by xzhangeb** [hytseng0509/CrossDomainFewShot#3]
Hi,
I downloaded the Plantae dataset from your link in the code, and I found that there are more than 2,900 classes. However, I checked the referenced paper where I saw the Plantae has only 2100 classes. Could you please tell me where how did you get the Plantae dataset?
Thx

**Comment by hytseng0509** [comment]
We use the 2018 set [here](https://github.com/visipedia/inat_comp/blob/master/2018/README.md). There are more categories compared to the 2017 one.
