### ISSUE TITLE
How to get the T-SNE effect in the paper

### ISSUE THREAD

**Issue by jianbingguozi60ge** [hytseng0509/CrossDomainFewShot#32]
I don't know how to get the data T-SNE renderings before and after the model process. Can you provide the corresponding T-SNE code, thank you very much!

**Comment by hytseng0509** [comment]
Hi,

Sorry that I don't have the script now, but I use T-SNE function [here](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html) and [ploty](https://plotly.com/) for plotting the figure.
