### ISSUE TITLE
Documentation on Plantae Dataset Version (iNat 2018)

### ISSUE THREAD

**Issue by itsnamgyu** [hytseng0509/CrossDomainFewShot#35]
It looks like the Plantae data is from the iNat 2018 dataset. Could you add some documentation on this detail? There seems to be no mention in the GitHub repo or your paper.

Thank you.

**Comment by hytseng0509** [comment]
Thanks for the information. We've already cited the CVPR18' paper in our paper in Section 4 and Appendix.
