### ISSUE TITLE
cars_train not found

### ISSUE THREAD

**Issue by JasonDu1993** [hytseng0509/CrossDomainFewShot#36]
The url http://imagenet.stanford.edu/internal/car196/cars_train.tgz is not used, what should I do?

**Comment by dota2mhxy** [comment]
i  had   same  problem  ,Please help solve it @hytseng0509

**Comment by hytseng0509** [comment]
I believe they update the link on the [official site](http://ai.stanford.edu/~jkrause/cars/car_dataset.html)
http://ai.stanford.edu/~jkrause/car196/cars_train.tgz
